### ISSUE TITLE
com.uchuhimo.konf.NameConflictException

### ISSUE THREAD

**Issue by brainoutsource** [uchuhimo/konf#11]
I have environment variables that I'd like to access via config specs:

```
export KAFKA_CLIENT_CERT=some_cert
export KAFKA_CLIENT_CERT_KEY=some_cert_key
```

Here's my config spec:

```
object KafkaConfigSpec : ConfigSpec("kafka") {
    val clientCert by optional(name="client.cert", default = "")
    val clientCertKey by optional(name="client.cert.key", default = "")
}
```

When I try to load the config:

```
Config { addSpec(KafkaConfigSpec) }.withSourceFrom.env()
```

I get the following stack trace:

```
Exception in thread "main" com.uchuhimo.konf.NameConflictException: item kafka.client.cert.key cannot be added
	at com.uchuhimo.konf.BaseConfig.addSpec(BaseConfig.kt:415)
	at com.uchuhimo.konf.Config$Companion.invoke(Config.kt:344)
```

**Comment by uchuhimo** [comment]
@brainoutsource In Konf, a key is parsed as a path split by ".". All paths in the same config are origanized as a tree, and every path should point to a leaf. Because "client.cert" is the parent of "client.cert.key", it is not a leaf and exception is thrown. You can change "KAFKA_CLIENT_CERT" to "KAFKA_CLIENT_CERT_NAME" or change "KAFKA_CLIENT_CERT_KEY" to "KAFKA_CLIENT_CERTKEY", then there is no name conflict. I hope this will help you.

**Comment by uchuhimo** [comment]
@brainoutsource There is another solution. you can change "client.cert.key" to "client.cert_key". There will be no name conflict.

**Comment by uchuhimo** [comment]
Can reopen this issue if further questions are encountered.
