### ISSUE TITLE
Cannot load a second version of the same config file schema

### ISSUE THREAD

**Issue by dennisschroeder** [uchuhimo/konf#26]
I need different contexts of the same config file schema in my project. So let´s say one has a **api.foo.yaml** and a **api.bar.yam**l in which we have the same keys but with different values.

```
// api.foo.yaml
database:
  host: foo.com

// api.bar.yaml
database:
  host: bar.com
```

And I create a Config class from each file it only has the foo values, since it was loaded first.
This is because the Spec classes are singeltons (object) in Kotlin.

I don´t know if I would consider it a issue. Maybe more a feature.

**Comment by uchuhimo** [comment]
@dennisschroeder Konf mimics hashmap when using a string key to retrieve the value, so the latter value with the same key will override the previous one. I think this behavior is expected.
In your use case, what is your expected behavior?

P.S. I'm sorry for the delay. It seems that Github often doesn't send me the notification emails of new issues.
