### ISSUE TITLE
combining configs is not working

### ISSUE THREAD

**Issue by lfmunoz** [uchuhimo/konf#35]
```
    val configDefault = Config {addSpec(ApplicationSpec)   }
      .from.yaml.resource("default.yml")


    val configEnv = Config{ addSpec(ApplicationSpec) }
      .from.env() // SERVER_HOST=0.0.0.0
      .from.systemProperties()  // -Dserver.host=0.0.0.0 -Dserver.port=8080


val totalConfig = configDefault + configLoad 

totalConfig.contains("value) // this will show true
totaConfig<String>("value) // this will fail

```

**Comment by uchuhimo** [comment]
@lfmunoz Can you provide a runnable code snippet for me to reproduce the bug? I cannot run your example code due to syntax error. Thanks!

**Comment by lfmunoz** [comment]
Thank you for this tool.  Full example of the problem:

```

import com.uchuhimo.konf.Config
import com.uchuhimo.konf.ConfigSpec


object AppSpec : ConfigSpec("server") {
  val port by required<String>()
  val username by optional<String>("ellis")
  val password by optional <String>("one23")

}

fun main(args: Array<String>) {

  val configEnv0 = Config{ addSpec(AppSpec) }
    .from.properties.string("server.username = ellisMODIFY")

  val configEnv1 = Config{ addSpec(AppSpec) }
    .from.properties.string("server.port = 8084")

  val totalConfig =   configEnv0 + configEnv1
  println(totalConfig.contains("server.port ")) // this will show FALSE (NOT OK)
  println(totalConfig<String>("server.port")) // this will return 8084 (OK)

  println(totalConfig) // this will show ellis  (NOT OK)

}
```

This produces

```
false
8084
Config(items={server.username=ellis, server.password=one23, server.port=8084})
```

I expected

```
true
8084
Config(items={server.username=ellisMODIFY, server.password=one23, server.port=8084})
```

**Comment by uchuhimo** [comment]
@lfmunoz `totalConfig.contains("server.port ")` returns `false` because of the trailing whitespace, it will return `true` if using `totalConfig.contains("server.port")`. `totalConfig<String>("server.username")` returns `"ellis"` because konf will search `configEnv1` for `"server.username"` first and find `"ellis"`, which will be directly returned. For the first issue, I can trim string before the search process in konf; for the second one, I'm not sure whether the values in fallback config should have higher priority than the default values in facade config.

**Comment by uchuhimo** [comment]
@lfmunoz I release v0.14.1 to solve these two issues. Now konf should work as you expected.
